configure: Add warnings in bold text to experimental features.
Signed-off-by: Joachim Nilsson <troglobit@gmail.com>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -38,127 +38,142 @@ TMP=`mktemp /tmp/XXXXXX`
 # Defaults
 disable_genid=0
 
+print()
+{
+    case $OS in
+	Linux)
+	    /bin/echo -ne "$*"
+	    ;;
+
+	*)
+	    printf "$*"
+	    ;;
+    esac
+}
+
 heading()
 {
-        echo "# This makefile snippet is generated by the pimd configure script." > $CFG
-        echo >> $CFG
-        echo "# Initial definitions ..." >> $CFG
-        echo "# -D_GNU_SOURCE Use GNU extensions, where possible" >> $CFG
-        echo "# -D_BSD_SOURCE Use functions derived from 4.3 BSD Unix rather than POSIX.1" >> $CFG
-        echo "# -DPIM         Enable PIM extensions in RSRR" >> $CFG
-        echo "DEFS          = -D_BSD_SOURCE -D_GNU_SOURCE -DPIM" >> $CFG
-        echo "# EXTRA_OBJS  = For locally provided objects missing on some platforms, e.g., strlcpy.o"  >> $CFG
-        echo "# EXTRA_LIBS  = For platform specific libraries, e.g., -lutil" >> $CFG
-        echo >> $CFG
-        echo "# $OS specific settings ..." >> $CFG
+    echo "# This makefile snippet is generated by the pimd configure script." > $CFG
+    echo >> $CFG
+    echo "# Initial definitions ..." >> $CFG
+    echo "# -D_GNU_SOURCE Use GNU extensions, where possible" >> $CFG
+    echo "# -D_BSD_SOURCE Use functions derived from 4.3 BSD Unix rather than POSIX.1" >> $CFG
+    echo "# -DPIM         Enable PIM extensions in RSRR" >> $CFG
+    echo "DEFS          = -D_BSD_SOURCE -D_GNU_SOURCE -DPIM" >> $CFG
+    echo "# EXTRA_OBJS  = For locally provided objects missing on some platforms, e.g., strlcpy.o"  >> $CFG
+    echo "# EXTRA_LIBS  = For platform specific libraries, e.g., -lutil" >> $CFG
+    echo >> $CFG
+    echo "# $OS specific settings ..." >> $CFG
 }
 
 usage()
 {
-        echo "Run this script to configure pimd for your operating system."
-        echo
-        echo "Usage: $0 [ARG]"
-        echo
-        echo "  --enable-broken-crc       Interop with older broken Cisco firmware that did"
-        echo "                            checksum in PIM Register messages slightly wrong."
-        echo "                            Should not be needed anymore."
-        echo "  --enable-kernel-encap     Some kernels can do PIM Register encapsulation by"
-        echo "                            themselves, this speeds up processing considerably"
-        echo "                            Only enable this if your kernel supports it"
-        echo "  --enable-kernel-mfc       Specialized kernels may have (*,G) MFC support."
-        echo "                            Only enable this if your kernel supports it."
-        echo "  --enable-memory-save      Save 4 bytes/unconfigured interface/routing entry"
-        echo "                            Must restart pimd and cause routing table to be"
-        echo "                            flushed when configuring new interfaces."
-        echo "  --enable-scoped-acls      Scoped access control list support in pimd.conf"
-        echo "                            phyint IFNAME [scoped <MCGROUP> masklen <LEN>]"
-        echo "                            phyint fxp0 scoped 239.0.0.0 masklen 8"
-        echo "  --enable-rsrr             Routing Support for Resource Reservations,"
-        echo "                            currently used by RSVP.  EXPERIMENTAL"
-        echo "  --disable-pim-genid       Disable Generation ID in PIM Hello, RFC3973"
-        echo
-        echo "  --disable-exit-on-error   Do not exit on error messages (LOG_ERR)"
-        echo "  --disable-masklen-check   Allow virtual tunctl VIFs with masklen 32"
-        echo
-        echo "  --with-includes=PATH      Use this if the multicast header files are not in"
-        echo "                            a standard location on your system. E.g., /sys"
-        echo "  --with-max-vifs=MAXVIFS   Kernel maximum number of allowed VIFs, default 32"
-        echo
-        echo "Report any bugs to https://github.com/troglobit/pimd/issues"
-        echo
+    print "Run this script to configure pimd for your system.\n"
+    print "\n"
+    print "Usage: configure [ARG]\n"
+    print "\n"
+    print "  --enable-broken-crc      Interop with older broken Cisco firmware that did\n"
+    print "                           checksum in PIM Register messages slightly wrong.\n"
+    print "                           Should not be needed anymore.\n"
+    print "  --enable-kernel-encap    Specialized kernels do PIM Register encapsulation\n"
+    print "                           by themselves, speeding up processing considerably.\n"
+    print "                           \e[1mNot on Linux/*BSD\e[0m, needs pimkern-PATCH_6!\n"
+    print "  --enable-kernel-mfc      Specialized kernels may have (*,G) MFC support.\n"
+    print "                           \e[1mNot on Linux/*BSD\e[0m, need pimkern-PATCH_7!\n"
+    print "  --enable-memory-save     Save 4 bytes/unconfigured interface/routing entry\n"
+    print "                           Must restart pimd and cause routing table to be\n"
+    print "                           flushed when configuring new interfaces.\n"
+    print "  --enable-scoped-acls     Scoped access control list support in pimd.conf\n"
+    print "                           phyint IFNAME [scoped <MCGROUP> masklen <LEN>]\n"
+    print "                           phyint fxp0 scoped 239.0.0.0 masklen 8\n"
+    print "  --enable-rsrr            Routing Support for Resource Reservations, defined in\n"
+    print "                           http://tools.ietf.org/html/draft-ietf-rsvp-routing-02\n"
+    print "                           currently used by RSVP.  \e[1mEXPERIMENTAL\e[0m\n"
+    print "\n"
+    print "  --disable-pim-genid      Disable Generation ID in PIM Hello, RFC3973\n"
+    print "  --disable-exit-on-error  Do not exit on error messages (LOG_ERR)\n"
+    print "  --disable-masklen-check  Allow virtual tunctl VIFs with masklen 32\n"
+    print "\n"
+    print "  --with-includes=PATH     Use this if the multicast header files are not in\n"
+    print "                           a standard location on your system. E.g., /sys\n"
+    print "  --with-max-vifs=MAXVIFS  Kernel maximum number of allowed VIFs, default 32\n"
+    print "                           \e[1mNote:\e[0m Try multiple routing tables instead!\n"
+    print "\n"
+    print "Report bugs to https://github.com/troglobit/pimd/issues\n"
+    print "\n"
 
-        exit 1
+    exit 1
 }
 
 echo > $TMP
 echo "# Enabled features ..." >> $TMP
 
 while [ "$*" != "" ]; do
-        opt=`expr "$1" : "--\([^=]*\)=.*"`
-        arg=`expr "$1" : "--[^=]*=\(.*\)"`
-        if [ -z "$opt" ]; then
-                opt=`expr "$1" : "--\(.*\)"`
-        fi
-        shift
+    opt=`expr "$1" : "--\([^=]*\)=.*"`
+    arg=`expr "$1" : "--[^=]*=\(.*\)"`
+    if [ -z "$opt" ]; then
+        opt=`expr "$1" : "--\(.*\)"`
+    fi
+    shift
 
-        case $opt in
-                enable-broken-crc)
-                        echo "DEFS         += -DBROKEN_CISCO_CHECKSUM" >> $TMP
-                        ;;
+    case $opt in
+        enable-broken-crc)
+            echo "DEFS         += -DBROKEN_CISCO_CHECKSUM" >> $TMP
+            ;;
 
-                enable-kernel-encap)
-                        echo "DEFS         += -DPIM_REG_KERNEL_ENCAP" >> $TMP
-                        ;;
+        enable-kernel-encap)
+            echo "DEFS         += -DPIM_REG_KERNEL_ENCAP" >> $TMP
+            ;;
 
-                enable-kernel-mfc)
-                        echo "DEFS         += -DKERNEL_MFC_WC_G" >> $TMP
-                        ;;
+        enable-kernel-mfc)
+            echo "DEFS         += -DKERNEL_MFC_WC_G" >> $TMP
+            ;;
 
-                enable-memory-save)
-                        echo "DEFS         += -DSAVE_MEMORY" >> $TMP
-                        ;;
+        enable-memory-save)
+            echo "DEFS         += -DSAVE_MEMORY" >> $TMP
+            ;;
 
-                enable-scoped-acls)
-                        echo "DEFS         += -DSCOPED_ACL" >> $TMP
-                        ;;
+        enable-scoped-acls)
+            echo "DEFS         += -DSCOPED_ACL" >> $TMP
+            ;;
 
-                enable-rsrr)
-                        echo "DEFS         += -DRSRR" >> $TMP
-                        echo "EXTRA_OBJS   += rsrr.o" >> $TMP
-                        ;;     
+        enable-rsrr)
+            echo "DEFS         += -DRSRR" >> $TMP
+            echo "EXTRA_OBJS   += rsrr.o" >> $TMP
+            ;;
 
-                enable-pim-hello-genid)
-                        echo "PIM Hello GenID is enabled by default."
-                        ;;
+        enable-pim-hello-genid)
+            echo "PIM Hello GenID is enabled by default."
+            ;;
 
-		disable-pim-genid)
-                        disable_genid=1
-                        ;;
+	disable-pim-genid)
+            disable_genid=1
+            ;;
 
-                disable-exit-on-error)
-                        echo "DEFS         += -DCONTINUE_ON_ERROR" >> $TMP
-                        ;;
+        disable-exit-on-error)
+            echo "DEFS         += -DCONTINUE_ON_ERROR" >> $TMP
+            ;;
 
-                disable-masklen-check)
-                        echo "DEFS         += -DDISABLE_MASKLEN_CHECK" >> $TMP
-                        ;;
+        disable-masklen-check)
+            echo "DEFS         += -DDISABLE_MASKLEN_CHECK" >> $TMP
+            ;;
 
-                with-includes)
-                        echo "INCLUDES     += -I$arg" >> $TMP
-                        ;;
+        with-includes)
+            echo "INCLUDES     += -I$arg" >> $TMP
+            ;;
 
-                with-max-vifs)
-                        echo "DEFS         += -DCUSTOM_MAX_VIFS=$arg" >> $TMP
-                        ;;
+        with-max-vifs)
+            echo "DEFS         += -DCUSTOM_MAX_VIFS=$arg" >> $TMP
+            ;;
 
-                help)
-                        usage
-                        ;;
+        help)
+            usage
+            ;;
 
-                *)
-                        echo "Skipping unknown option: $opt"
-                        ;;
-        esac
+        *)
+            echo "Skipping unknown option: $opt"
+            ;;
+    esac
 done
 
 if [ $disable_genid -ne 1 ]; then
@@ -198,45 +213,45 @@ fi
 #EXTRA_OBJS   = strlcpy.o pidfile.o
 #EXTRA_LIBS   = -L/usr/ucblib -lucb -L/usr/lib -lsocket -lnsl
 case $OS in
-        Linux)
-                heading
-	        echo "INCLUDES     = -Iinclude" >> $CFG
-	        echo "DEFS        += -DRAW_OUTPUT_IS_RAW -DIOCTL_OK_ON_RAW_SOCKET" >> $CFG
-		echo "ROUTER_OBJS += netlink.o" >> $CFG
-	        echo "EXTRA_OBJS   = libite/strlcpy.o libite/strlcat.o" >> $CFG
-	        echo "EXTRA_OBJS  += libite/pidfile.o libite/strtonum.o" >> $CFG
-	        echo "EXTRA_LIBS   =" >> $CFG
-	        ;;
+    Linux)
+        heading
+	echo "INCLUDES     = -Iinclude" >> $CFG
+	echo "DEFS        += -DRAW_OUTPUT_IS_RAW -DIOCTL_OK_ON_RAW_SOCKET" >> $CFG
+	echo "ROUTER_OBJS += netlink.o" >> $CFG
+	echo "EXTRA_OBJS   = libite/strlcpy.o libite/strlcat.o" >> $CFG
+	echo "EXTRA_OBJS  += libite/pidfile.o libite/strtonum.o" >> $CFG
+	echo "EXTRA_LIBS   =" >> $CFG
+	;;
 
-        FreeBSD)
-                heading
-	        echo "INCLUDES     =" >> $CFG
-		echo "ROUTER_OBJS += routesock.o" >> $CFG
-	        echo "EXTRA_OBJS   = libite/pidfile.o" >> $CFG
-	        echo "EXTRA_LIBS   =" >> $CFG
-	        ;;
+    FreeBSD)
+        heading
+	echo "INCLUDES     =" >> $CFG
+	echo "ROUTER_OBJS += routesock.o" >> $CFG
+	echo "EXTRA_OBJS   = libite/pidfile.o" >> $CFG
+	echo "EXTRA_LIBS   =" >> $CFG
+	;;
 
-        NetBSD)
-                heading
-	        echo "INCLUDES     =" >> $CFG
-		echo "ROUTER_OBJS += routesock.o" >> $CFG
-	        echo "EXTRA_OBJS   = libite/strtonum.o" >> $CFG
-	        echo "EXTRA_LIBS   = -lutil" >> $CFG
-	        ;;
+    NetBSD)
+        heading
+	echo "INCLUDES     =" >> $CFG
+	echo "ROUTER_OBJS += routesock.o" >> $CFG
+	echo "EXTRA_OBJS   = libite/strtonum.o" >> $CFG
+	echo "EXTRA_LIBS   = -lutil" >> $CFG
+	;;
 
-        OpenBSD)
-                heading
-	        echo "INCLUDES     =" >> $CFG
-		echo "ROUTER_OBJS += routesock.o" >> $CFG
-	        echo "EXTRA_OBJS   =" >> $CFG
-	        echo "EXTRA_LIBS   = -lutil" >> $CFG
-	        ;;
+    OpenBSD)
+        heading
+	echo "INCLUDES     =" >> $CFG
+	echo "ROUTER_OBJS += routesock.o" >> $CFG
+	echo "EXTRA_OBJS   =" >> $CFG
+	echo "EXTRA_LIBS   = -lutil" >> $CFG
+	;;
 
-        *)
-	        rm $CFG
-	        echo "$OS is currently unsupported.  Help out at https://github.com/troglobit/pimd/"
-	        exit 1
-	        ;;
+    *)
+	rm $CFG
+	echo "$OS is currently unsupported.  Help out at https://github.com/troglobit/pimd/"
+	exit 1
+	;;
 esac
 
 cat $TMP >> $CFG
